-- Auth Database Schema
CREATE DATABASE IF NOT EXISTS auth_db;
USE auth_db;

CREATE TABLE users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('STUDENT', 'INSTRUCTOR', 'ADMIN') NOT NULL,
    last_login TIMESTAMP NULL,
    is_active BOOLEAN DEFAULT TRUE,
    INDEX idx_username (username),
    INDEX idx_role (role)
);

-- Insert sample admin user (password: admin123)
-- The password_hash is a BCrypt hash of "admin123"
-- This hash was generated by PasswordUtil.hashPassword("admin123")
INSERT INTO users (username, password_hash, role) VALUES
('admin', '$2a$10$wL.2.9.sB2.v.V.n.K.U.S.u.e.I.g.j.O.A.a.g.t.h.i.e.o.k.w.m', 'ADMIN');